export { default as IconPhoto } from './IconPhoto'
export { default as IconStar } from './IconStar'
export { default as IconArrowRight } from './IconArrowRight'
export { default as IconCheck } from './IconCheck'
export { default as IconBeranda } from './IconBeranda/index'
export { default as IconBerandaSolid } from './IconBeranda/solid'
export { default as IconQr } from './IconQr'
export { default as IconGaCare } from './IconGaCare'
export { default as IconProfile } from './IconProfile/index'
export { default as IconProfileSolid } from './IconProfile/solid'
export { default as IconBell } from './IconBell'
export { default as IconNews } from './IconNews'
export { default as IconEdit } from './IconEdit'

